{% set version = "1.6.0" %}

package:
  name: hmat-oss
  version: {{ version }}

source:
  fn: hmat-oss-{{ version }}.tar.gz
  url: https://github.com/jeromerobert/hmat-oss/archive/{{ version }}.tar.gz
  sha256: 441bffb2e578150d86b0f056a52a3838f56d0bef6c6257c1bf6f54b308f37125
  patches:
    - disable-werror.patch
    - link_public.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('hmat-oss', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - liblapack
    - libcblas

test:
  commands:
    - test -f ${PREFIX}/include/hmat/hmat/hmat.h  # [unix]
    - test -f ${PREFIX}/lib/libhmat-oss${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/jeromerobert/hmat-oss
  license: GPLv2
  license_file: LICENSE.md
  summary: A hierarchical matrix C/C++ library

extra:
  recipe-maintainers:
    - jschueller
