{% set version = "1.10.0" %}

package:
  name: hmat-oss
  version: {{ version }}

source:
  fn: hmat-oss-{{ version }}.tar.gz
  url: https://github.com/jeromerobert/hmat-oss/archive/{{ version }}.tar.gz
  sha256: 357969e54d4d213cbab9c0eb4ca944a160d519b0790c8300431b4acc151387e5

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('hmat-oss', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - libtmglib
    - liblapacke
    - libcblas

test:
  commands:
    - test -f ${PREFIX}/include/hmat/hmat.h  # [unix]
    - test -f ${PREFIX}/lib/libhmat${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/jeromerobert/hmat-oss
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  summary: A hierarchical matrix C/C++ library

extra:
  recipe-maintainers:
    - jschueller
