{% set version = "1.5.0" %}

package:
  name: hmat-oss
  version: {{ version }}

source:
  fn: hmat-oss-{{ version }}.tar.gz
  url: https://github.com/jeromerobert/hmat-oss/archive/{{ version }}.tar.gz
  sha256: 21a64d1df1c9bb7221205020b95af8bff65668d0d2cfde5431d0e9fc7958d0a9
  patches:
    - disable-werror.patch
    - link_public.patch

build:
  number: 206
  skip: true  # [win]
  features:

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - liblapack
    - libcblas

test:
  commands:
    - test -f ${PREFIX}/include/hmat/hmat/hmat.h  # [unix]
    - test -f ${PREFIX}/lib/libhmat-oss${SHLIB_EXT}  # [unix]

    - conda inspect linkages -p ${PREFIX} hmat-oss  # [not win]
    - conda inspect objects -p ${PREFIX} hmat-oss  # [osx]

about:
  home: https://github.com/jeromerobert/hmat-oss
  license: GPLv2
  license_file: LICENSE.md
  summary: A hierarchical matrix C/C++ library

extra:
  recipe-maintainers:
    - jschueller
