# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JgaLn4ygyGDWb9Uz9Fhx3Er9V8BqZXp36i0EPUQxKb1QL7vwdPzAR+yamkowWMZq7k/Duj8esA2RjvXK8WwpiCC7Q0a4ATZPPzwRz5CbP4Ckm4DtT7rplDa+XjiMl2Pq+IFwpKW9sgxcxMKwvxrCXykcWVNK1PJkID6SaMPhJmZnFq3gfvy1kWl42AMeQU51u49g/7shiaUxBC5lJH7fv9gczMpiGC+OnfvJlmDDTgOPLvNBTUCgzeQsD/mk/utojBa7700WF26GI+av8tb3T2+lbxKlmFFpKTRaoDijQgNex12EBzt/f+5lHULGwVLcD8Z6OD6k1WjlPp0HrYjiZ3uvViz7XOStm3Bz4QmeMV5N2cqw4LLVSkKSsQTjkuE9lGtqSmmuq0t9KzRKQRNu5NUavKiAxLdAU9MQpKmLWUkxpYA3hMHiR8ErVfe4lAxXBudUG9E6A6umr7ailKjXI0XK8e/WLz56PzAz05JjzqLVDl1B513XMyv/i00rS3FutnxIIKb5G4xsYPfRYmm+RPWzGKQl1UaGP6vRPK1q3k0UCAKw7rMW/PuCIiseeX5B4YFrWH9QTsS5zo93BQ5LnW64YSM7gUVM3m/gbS+MM69CJEs0Asty5sVp32Dst2nl2POuYDYp57I6k/CYvuebAQ5QiL5gKWfzBek5ieKZDDc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml