travis:
  secure:
    BINSTAR_TOKEN: mzHR9LJMAr8YuWMpxADdDe9V8W/mtVzDNjnX7lpmcqJiGHx3qP4EiJjMOfTXF1zng4y0Gj6aJJysVs+Z1G8TR/lxNOGjegQ492MrYPSTiGdRYOsUvMFITLWyZ17jA+gFvWS5j6fz/Pz5O+85O60bH/VTiA1BgU0iU1Ip1vu7GSnLFkJNSleAi8YYgFJkWFQB+dxjIAxfVti9MRUVO74c5Qw0S7vWL9/Z53ODxwTz9ZZ3l97klmj+DKRTnaKTiiZZpbdzj/gmm+urulQB3QoK36Mv9E3JPR/eh+GA+YS5XZNnotSN2DdUXXmbXo/uDHebnXw/W8UwXRrxm6LsDiWSZKY1DRYX8UkZ3FPnw9WCxm+YlB7KYyFQapIQvIEESKPwifZ/7RLy8rP9HWDXgSbLJz4IiWwmMKseIV05E/2tqVRYw/77oyBK1dX3M1itVYCjvsCGUYsruV3lhoBSTRXmIoyFoZzNyWmUpFLNhumswnZQYrYiOlpWF7kjfvSlupzJ0AK+Qg7d4Hgxc46a/r04Jv26mc/zlHlqtlM97Hw3LSL8qNISaMBoJOn1uxn44hMei31CIU2vwlsh30L9izTuSYosKJa4OARl+qEJOprttKxQu7A4qysFVIqDJpHLFTyZQaSGHgL2tfb0qp7FGdYw2xZC28raBH8tdaJ4UOvnBIs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
