travis:
  secure:
    BINSTAR_TOKEN: JgaLn4ygyGDWb9Uz9Fhx3Er9V8BqZXp36i0EPUQxKb1QL7vwdPzAR+yamkowWMZq7k/Duj8esA2RjvXK8WwpiCC7Q0a4ATZPPzwRz5CbP4Ckm4DtT7rplDa+XjiMl2Pq+IFwpKW9sgxcxMKwvxrCXykcWVNK1PJkID6SaMPhJmZnFq3gfvy1kWl42AMeQU51u49g/7shiaUxBC5lJH7fv9gczMpiGC+OnfvJlmDDTgOPLvNBTUCgzeQsD/mk/utojBa7700WF26GI+av8tb3T2+lbxKlmFFpKTRaoDijQgNex12EBzt/f+5lHULGwVLcD8Z6OD6k1WjlPp0HrYjiZ3uvViz7XOStm3Bz4QmeMV5N2cqw4LLVSkKSsQTjkuE9lGtqSmmuq0t9KzRKQRNu5NUavKiAxLdAU9MQpKmLWUkxpYA3hMHiR8ErVfe4lAxXBudUG9E6A6umr7ailKjXI0XK8e/WLz56PzAz05JjzqLVDl1B513XMyv/i00rS3FutnxIIKb5G4xsYPfRYmm+RPWzGKQl1UaGP6vRPK1q3k0UCAKw7rMW/PuCIiseeX5B4YFrWH9QTsS5zo93BQ5LnW64YSM7gUVM3m/gbS+MM69CJEs0Asty5sVp32Dst2nl2POuYDYp57I6k/CYvuebAQ5QiL5gKWfzBek5ieKZDDc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
